name: temp-behavior-env
channels:
    - conda-forge
dependencies:
    - ipykernel
    - matplotlib=3.2
    - numpy=1.18
    - pandas=1.0
    - python=3.8
    - scipy=1.4
    - seaborn=0.10
    - statsmodels=0.11